#!/bin/sh
CM_MAJOR_VERSION=6
CM_MINOR_VERSION=3
CM_PATCH_VERSION=1
CM_VERSION=${CM_MAJOR_VERSION}.${CM_MINOR_VERSION}.${CM_PATCH_VERSION}
CLOUDERA_BASE_URL=https://archive.cloudera.com/cm${CM_MAJOR_VERSION}/${CM_VERSION}/ubuntu1804/apt/

# Add user to sudoers (required by cloudera manager)
sudo cp /etc/sudoers.orig /etc/sudoers
echo "bigdata ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers.d/bigdata

# #############################################################################
# Install required packages
sudo apt update
sudo apt install --yes \
        wget gnupg2 ca-certificates vim ntp git \  # installing some utilities
        net-utils \                                # installing some utilities
        oracle-j2sdk1.8 \                          # installing java (error with openjdk-8-jdk)
	mysql-server libmysql-java mysql-workbench # installing mysql and java connector
# End - Install
# #############################################################################

# #############################################################################
# Enable NTP
sudo ufw allow from any to any port 123 proto udp
sudo service ntp restart
# End - NTP
# #############################################################################

# #############################################################################
# Enable MySQL

# Clean Mysql install and start from scratch
# sudo apt-get remove --purge mysql-server mysql-client mysql-common -y
# sudo apt-get autoremove -y
# sudo apt-get autoclean
# sudo rm -rf /etc/mysql
# sudo find / -iname 'misql*' -exec sudo rm -rf{} \;

sudo /etc/init.d/mysql start
sudo mysql -u root < mysql/config.sql
# End - MySQL
# #############################################################################

# #############################################################################
# Enable CDH
# sudo rm -r /etc/apt/sources.list.d/*
# sudo wget -q https://archive.cloudera.com/cm6/6.3.1/ubuntu1804/apt/cloudera-manager.list -P /etc/apt/sources.list.d
# sudo wget -q https://archive.cloudera.com/cm6/6.3.1/ubuntu1804/apt/archive.key -O - | sudo apt-key add - 
sudo wget -q ${CLOUDERA_BASE_URL}/cloudera-manager.list -P /etc/apt/sources.list.d
sudo wget -q ${CLOUDERA_BASE_URL}/archive.key -O - | sudo apt-key add - 
sudo rm -rf /var/lib/apt/lists/*
# Install cloudera-manager-{server,daemons,agent}
sudo apt update
sudo apt install --yes cloudera-manager-daemons cloudera-manager-agent cloudera-manager-server
sudo rm -rf /var/lib/apt/lists/*
# sudo cp db.properties /etc/cloudera-scm-server/db.properties -- generated by the following command
sudo /opt/cloudera/cm/schema/scm_prepare_database.sh mysql scm scm password
sudo ufw allow 7182
# End - CDH
# #############################################################################

# #############################################################################
# Enable SSH
sudo apt install -y openssh-server
sudo ufw allow ssh
sudo systemctl enable --now ssh
# End - SSH
# #############################################################################

# chmod +x docker-entrypoint.sh
# sudo ./docker-entrypoint.sh start &
sudo service cloudera-scm-server start
# Check the logs here!!!
# sudo tail -f /var/log/cloudera-scm-agent/cloudera-scm-agent.log
sudo tail -f /var/log/cloudera-scm-server/cloudera-scm-server.log

