alter user 'root'@'localhost' identified by 'password';
create database if not exists scm;
create database if not exists hive;
create database if not exists oozie;
create database if not exists hue;
create user if not exists 'scm'@'localhost' identified by 'password';
grant all privileges on *.* to 'scm'@localhost with grant option;
create user if not exists 'hive'@'localhost' identified by 'password';
grant all privileges on hive.* to 'hive'@localhost;
create user if not exists 'oozie'@'localhost' identified by 'password';
grant all privileges on oozie.* to 'oozie'@localhost;
create user if not exists 'hue'@'localhost' identified by 'password';
grant all privileges on hue.* to 'hue'@localhost;
